name: redparking
description: A new Flutter project.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  http: ^1.2.2
  intl: ^0.20.2
  flutter_svg: ^2.0.9  # Actualizado a una versión compatible
  android_intent_plus: ^5.3.0  # Asegúrate de usar la última versión
  permission_handler: ^11.3.0  # Agregado para manejar permisos

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: 5.4.4
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Isotipo-Red-Parking-Color-PNG-RGB.png
    - assets/Logotipo-Red-Parking-Color-PNG-RGB.png
    - assets/Logotipo-Red-Parking-Blanco-PNG-RGB.png